### PR TITLE
added support for DTBook 1.1.0 when converting from nordic epub to dtboo...

### PR DESCRIPTION
**Pull request by ybk**
We have inserted an option in the step Nordic EPUB3 to DTBook to convert to DTBook 1.1.0 (used by Nota) which is set to true as default (default is DTBook 2005). The actual conversion is executed by a stylesheet from DTBook 2005 to DTBook 1.1.0.
These changes only works when pull from jostein daisy/pipeline-scripts#63 is merged into dtbook-validator.

### CODE REVIEW

**Comment by josteinaj** [comment]
The dtbook110 branch is now ready to be merged into the master branch, but I will wait until maybe next week to do so since i just released a new version and i don't want to release more than one version each week.

There were some conflicts between the dtbook110 branch here and my local version when I rebased it to the newest commit on the master branch, but the differences seems not to have been important (mainly whitespaces etc), so I renamed the original dtbook110 branch to dtbook110-ybk in case you need it.

**Comment by ybk** [comment]
Ok, that sounds great. Are the changes you made on dtbook-validator merged in and if so, where can i get newest version?

**Comment by josteinaj** [comment]
I have not merged anything to the master branch yet. You can check out the branch in this pull request (dtbook110) if you want to try out the changes (it's rebased on top of the latest released build so everything should be included).

I've fixed some issues in the `issue-236-292-293-296-270-294`-branch (not merged, will merge with dtbook110 before merging to master). I'm currently working on a refactoring in `more-scripts-2015-02` which will result in more scripts (single-HTML-related) being made available (epub3-to-html, html-to-dtbook, dtbook-to-html, html-to-epub3, html-validator) as well as an experimental EPUB3 ASCIIMath/MathML script which replaces all asciimath with MathML. But the `dtbook110` branch has not been merged into there yet either. Since the latest build is pretty stable, I want to wait a bit before releasing a new build, so the next build will probably not be until early march.

**Comment by ybk** [comment]
it's working fine, thanx a lot :-)

**Comment by josteinaj** [comment]
No problem. Glad to hear it works :)


Jostein

**Comment by josteinaj** [comment]
@ybk these changes are now available in the latest build.

**Comment by ybk** [comment]
@josteinaj ok great, thank you

**Pull request merged**
