### PR TITLE
Allow hr in poems

### PR DESCRIPTION
**Pull request by kalaspuffar**
Hi @josteinaj 

We have seen the usage of Horizontal rules in books within poems to mark essential breaks in the flow. I've made a small change to the RNG to allow for this.

Best regards
Daniel

### CODE REVIEW

**Comment by kalaspuffar** [comment]
Hi @josteinaj 

I saw two more file changes, those a bugfixes for the flow. I thought we already had handled them.

Best regards
Daniel

**Comment by kalaspuffar** [comment]
Hi.

Added a test case as well to ensure functionality.

Best regards
Daniel

**Comment by josteinaj** [comment]
Hi.

While the code looks good, this is not mentioned as an option in the guidelines:
https://format.mtm.se/nordic_epub/2020-1/#poetry-and-verse

I think we need to release a version of the validator for 2020-1 before we start revising the guidelines.

**Comment by martinpub** [comment]
Hi everyone. I agree with @josteinaj, even though there is a strong case for using separators in verse markup, as it is common in poems.

However, an observation is that the "Poetry and verse" section in 2020-1 does not forbid hr thematic break, and that "provid[ing] distinguishable paragraph-level thematic breaks" ("3.5 Thematic Breaks in the Text Flow") through hr markup could be interpreted as applicable also in verse settings.

I don't see any other good ways of marking up poems with stanzas separated by e.g. asterisks to indicate thematic breaks in 2020-1 if this is disallowed.

FIY: me, @oscarlcarlsson and @AndersEkl have started planning for a guidelines revision, more info with a draft plan will be available soon.

**Comment by AndersEkl** [comment]
Like @martinpub said, there is nothing in the 2020-1 guidelines that forbids the use of thematic breaks in a poetry and verse context. I would not object to the validator allowing it. And we can make it clearer in the upcoming revision that it is allowed.

**Comment by karladamt** [comment]
@josteinaj it would help us a lot if we could merge this now, it is blocking some titles for us as we are transending to epub.

**Review by josteinaj — APPROVED** [review]

**Pull request merged**
