### PR TITLE
Test book constructions

### PR DESCRIPTION
**Pull request by martinpub**
Starting adding things to test book (see #450)

### CODE REVIEW

**Comment by martinpub** [comment]
Hi @kalaspuffar, don't know why an automatic merge is not possible here? I cannot see the conflicting files? https://github.com/nlbdev/nordic-epub3-dtbook-migrator/compare/guidelines-revision...martinpub:guidelines-revision. Any chance you can help out a less git-skilled friend? :)

**Comment by kalaspuffar** [comment]
Hi @martinpub 

Are you done with this PR, or will you make more changes? I see that this one needs to be rebased to merge it. Can you do that, or do you want me to rebase and create a PR against your PR?

Best regards
Daniel

**Comment by martinpub** [comment]
Thanks @kalaspuffar, I will still add more test construction so I guess we can leave this open for a little longer. Will probably get back to you regarding the rebase, as I'm not 100% sure how to do it.

**Comment by martinpub** [comment]
Seems like I got stuck in a loop here @kalaspuffar, thought I fixed it but apparently not. git help?

**Comment by martinpub** [comment]
Replaced by #468, but the merge problems are still there.

**Pull request closed without merging**
