### PR TITLE
Webpage update

### PR DESCRIPTION
**Pull request by martinpub**
Hi @josteinaj!

This PR starts an update of the Nordic Migrator web page, preparing for an official release (following #396).

So far, I have updated the structure and gone through the About section, let me know what you think.

I suggest we leave this PR open until we are ready to publish (and I guess the GH web page is based directly off of the state of the gh-pages branch), so more commits will follow before it's ready for merging.

### CODE REVIEW

**Comment by martinpub** [comment]
Hi again @josteinaj, I added an update of the Resources section.

- Changed links to EPUB guidelines documents now published on format.mtm.se
- Removed outdated links
- Grouped links

A question, should we make an updated list of validation rules for 2020-1 guidelines? I have a vague memory of us/Hugo starting on something like that early on in the guidelines update process? Noting that this is only for 2015-1 at the moment, sticking with minimally required updates at this point. But it would be nice to point to something similar for 2020-1 guidelines.

Next, i will turn my attention to testing the installation methods again from a user perspective, and see if there are any changes/clarifications to be done in that section.

**Comment by josteinaj** [comment]
Hi @martinpub. Looks great!

Yes, let's wait with merging until we release a new version.

Having an updated list of validation rules for 2020-1 would be useful, but maybe not required for making a release. It's good that you remembered it, I had totally forgot about it. There's a couple of 2020-XSLTs here thatwe can run: https://github.com/nlbdev/nordic-epub3-dtbook-migrator/tree/guidelines-revision/documentation

**Comment by josteinaj** [comment]
I've made a release now. Version 1.5.0:

- Maven repository (now on Github): https://github.com/nlbdev/nordic-epub3-dtbook-migrator/tree/mvn-repo/org/daisy/pipeline/modules/nordic-epub3-dtbook-migrator/1.5.0
- Github release: https://github.com/nlbdev/nordic-epub3-dtbook-migrator/releases/tag/v1.5.0

The Docker image has not finished building yet, but unless something goes wrong, it will be available very soon: https://hub.docker.com/r/nlbdev/nordic-epub3-dtbook-migrator

**Comment by martinpub** [comment]
Great work @josteinaj!

Will continue with the docs update.

BTW, did you see [my question](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/issues/396#issuecomment-1103619691) in #396?

**Comment by josteinaj** [comment]
Hi @martinpub. I haven't had time to look at it yet but it doesn't hurt to add it, as you say, and we can improve it later if needed.

**Comment by martinpub** [comment]
> Hi @martinpub. I haven't had time to look at it yet but it doesn't hurt to add it, as you say, and we can improve it later if needed.

OK, great. Logged this task separately in https://github.com/nlbdev/nordic-epub3-dtbook-migrator/issues/513, will leave it as is for now.

**Review by josteinaj — APPROVED** [review]

**Comment by josteinaj** [comment]
@martinpub can I merge this now or do you want to make more changes first?

**Comment by martinpub** [comment]
Hi @josteinaj, I have some minor edits left, and was still thinking about how best to phrase the Docker instructions, which will be most important.

**Comment by martinpub** [comment]
Hi again @josteinaj, made some additions now. What do you think about this?  I have tried to strike a balance between a somewhat user-friendly explanation of the easiest way to run the migrator while not getting too deep into the specifics of various Docker setups.

Are there any updates to be made to the Pipeline 2 updater section based on the current release status?

Ping also @AndersEkl, do you see any obvious things we need to add/change?

If you both approve the changes, I guess they can be merged now. If we get questions later on, we can clarify and update the web page docs.

**Comment by AndersEkl** [comment]
> Ping also @AndersEkl, do you see any obvious things we need to add/change?

Where should I go in and read?

**Comment by martinpub** [comment]
> @martinpub Where should I go in and read?

Yeah, sorry, probably not the most straight-forward in a pending PR, but here is [a link to index.html in the PR](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/a233d16356864507a8b2383f4dbbeff614dffb11/index.html), where most of the changes are at.

**Comment by josteinaj** [comment]
I'm just gonna merge this one. We can easily adjust it later if needed (either directly or in a PR).

**Comment by martinpub** [comment]
> I'm just gonna merge this one. We can easily adjust it later if needed (either directly or in a PR).

Thanks @josteinaj!

**Pull request merged**
